### ISSUE TITLE
Make font configurable

### ISSUE THREAD

**Issue by NorbertHuethmayr** [AOEpeople/cookie-notice#10]
Hi,

wouldn't it make sense to have the font configurable as well?

Best regards
Norbert

**Comment by BernhardBehrendt** [comment]
It's now possible to set a `fontFamily` param to set a custom font (default is ìnherit`to match the template font if already set

```
<script>
    new cookieNoticeJS({
        fontFamily: 'Comic Sans MS,Verdana,Helvetica'
    })
</script>
```

![Bildschirmfoto 2020-01-02 um 16 16 22](https://user-images.githubusercontent.com/1717382/71674356-44663e00-2d7b-11ea-9982-03ff0ca0a54d.png)
