### ISSUE TITLE
Suggestion - Add pt language

### ISSUE THREAD

**Issue by fgrazi** [AOEpeople/cookie-notice#11]
Hi there, sorry, I do not know how to contribute to open source projects, but if you wish to add Portuguese language here is the translation you need:

Line 25 of cookie.notice.js:

 pt: 'Utilizamos cookies para garantir que você tenha a melhor experiência em nosso site. Se você continuar a usar este site, assumimos que você aceita isso.'

Line 39 of cookie.notice.js:
            pt: 'Saber mais'

Congratulations for the excellent code!

**Comment by BernhardBehrendt** [comment]
Happy new year @fgrazi and thanks for the translations.I've added it and it's available via [npm](https://www.npmjs.com/package/cookie-notice) with version **1.2.1**
