### ISSUE TITLE
Link to the fork on the main repo and some advise about GDPR compliance.

### ISSUE THREAD

**Issue by micc83** [AOEpeople/cookie-notice#7]
Hi,
Sorry if I didn't show up before. I've linked your fork on [CookieNoticeJS readme file](https://github.com/micc83/cookie-notice-js/blob/master/README.md). 

Also, about GDPR compliance, In order for the script to be an all-in-one solution for handling Cookies acceptance it should have some way to block cookie injecting scripts on page first load (or at least the most common ones: analytics, facebook, tripadvisor, gmaps, etc... with some way to add custom ones) and eventually load them when the policy is accepted (by clicking on the ACCEPT button or, as long as permitted by GDPR, by scrolling the page). Hope that helps.

Cheers

**Comment by BernhardBehrendt** [comment]
Think that is not safe to realize because it depends in which order 3rd party scripts are included.
